[package]
name = "aoc-helper"
version = "0.1.1"
edition = "2021"

[dependencies]
# reqwest= { version = "0.11", features = ["blocking"] } 
clap = "2"
dirs = "4.0"
chrono = "0.4"
# itertools = "0.10.1"
ureq = "*"
